name: Update testops DB - demo data 

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Update testops database 
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set ENV vars 
        run: |
          echo "CLOUD_SQL_DATABASE_USERNAME=${{ secrets.CLOUD_SQL_DATABASE_USERNAME }}" >> $GITHUB_ENV
          echo "CLOUD_SQL_DATABASE_PASSWORD=${{ secrets.CLOUD_SQL_DATABASE_PASSWORD}}" >> $GITHUB_ENV
          echo "CLOUD_SQL_DATABASE_NAME=${{ secrets.CLOUD_SQL_DATABASE_NAME}}" >> $GITHUB_ENV

      - name: Setup python 
        uses: actions/setup-python@v1

      - name: Establish Cloud SQL Proxy 
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GCLOUD_AUTH }}
          instance: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
          port: 3306

      - name: Insert data 
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: python ./base_demo.py 

