name: Update testops database: demo data 

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Update testops database 
    runs-on: ubuntu-latest

    steps:
      - name: Insert data 
        uses: mattes/gce-cloudsql-proxy-action@v1
	with:
	  #creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
	  creds: ${{ secrets.GCLOUD_AUTH }}
          instance: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
        uses: actions/checkout@v2
        uses: actions/setup-python@v1
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: python ./base_demo.py 

