name: Update testops DB - demo data 

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Update testops database 
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup python 
        uses: actions/setup-python@v1

      - name: Establish Cloud SQL Proxy 
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH}}
          CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME}}
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GCLOUD_AUTH }}
          instance: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
          port: 3307

      - name: Insert data 
        env:
          CLOUD_SQL_DATABASE_USERNAME: ${{ secrets.CLOUD_SQL_DATABASE_USERNAME }}
          CLOUD_SQL_DATABASE_PASSWORD: ${{ secrets.CLOUD_SQL_DATABASE_PASSWORD }}
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: python ./base_demo.py 

