name: Update testops DB - demo data 

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Update testops database 
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup python 
        uses: actions/setup-python@v1

      - name: Insert data 
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GCLOUD_AUTH }}
          instance: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: python ./base_demo.py 

