name: Send custom JSON data to Slack workflow

on:
  push:
    branches:
      - slack-demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Setup python 
        uses: actions/setup-python@v1
 
      - name: Install requirements 
        run: pip install -r requirements.txt 
 
      - name: Run telemetry probe expiry check 
        run: python ./check_metrics.py 

      - name: Demo Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload-file-path: "./slack-payload.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST_ALERTS_SANDBOX }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

