name: Testops Report WEEKLY 

# Sat. @4am UTC
on:
  schedule:
    - cron:  "0 4 * * 6" 
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/update-testops-db.yml
    with:
      project_name: "ALL"
      frequency: "Weekly"
      is_update_db: true