name: Testops Report PUSH 

on:
  push:
    branches:
      - master
      - reusable-workflow 

jobs:
  deploy:
    uses: ./.github/workflows/update-testops-db.yml
    with:
      project_name: "fenix"
      frequency: "Daily"
      is_update_db: true