name: Testops Report DAILY 

# UTC Daily @4am
on:
  schedule:
    - cron:  "0 4 * * *" 

on:
  push:
    branches:
      - testrail-test-runs

jobs:
  deploy:
    name: Update testops DB 
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup python 
        uses: actions/setup-python@v1

      - name: Establish Cloud SQL Proxy
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
          CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GCLOUD_AUTH }}
          instance: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
          port: ${{ secrets.CLOUD_SQL_DATABASE_PORT }}

      - name: Install requirements 
        run: pip install -r requirements.txt

      - name: Insert data
        env:
          CLOUD_SQL_DATABASE_USERNAME: ${{ secrets.CLOUD_SQL_DATABASE_USERNAME }}
          CLOUD_SQL_DATABASE_PASSWORD: ${{ secrets.CLOUD_SQL_DATABASE_PASSWORD }}
          CLOUD_SQL_DATABASE_NAME: ${{ secrets.CLOUD_SQL_DATABASE_NAME }}
          CLOUD_SQL_DATABASE_PORT: ${{ secrets.CLOUD_SQL_DATABASE_PORT }}
          TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST}}
          TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME}}
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD}}
        #run: python ./data_pump.py --report-type test-runs --project fenix 
        #run: python ./data_pump.py --report-type test-cases --project fenix 
        run: |
            echo "Testops Report: DAILY"

